services:
  postgres:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - mood_tracker_network
    ports:
      - "44887:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:top2gun6@postgres:5432/postgres
      STATIC_API_KEY: ${STATIC_API_KEY}
    networks:
      - mood_tracker_network
    ports:
      - "1847:1847"
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:1847
      STATIC_API_KEY: ${STATIC_API_KEY}
    networks:
      - mood_tracker_network
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  mood_tracker_network:
    external: true
    driver: bridge

volumes:
  postgres:
